development:
    adapter: sqlite3
    database: db/development.sqlite3
    pool: 5
    timeout: 5000
development_mysql_osx:
    adapter: mysql2
    encoding: utf8
    username: balder
    password: changeme
    database: balder_development
    socket: /tmp/mysql.sock
production:
    adapter: mysql2
    encoding: utf8
    username: balder
    password: changeme
    database: balder_production
    socket: /var/run/mysqld/mysqld.sock
test: &TEST
    adapter: postgresql
    database: gallery_test
    username: balder
    password: changeme